services:
  - type: web
    runtime: python
    pythonVersion: 3.9.16
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn blood_grp:app --bind 0.0.0.0:$PORT
    env:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000 