services:
  - type: web
    name: blood-group-predictor
    env:
      - key: PYTHON_VERSION
        value: 3.9.3
    buildCommand: pip install -r requirements.txt
    startCommand: python your_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13 