services:
  - type: web
    runtime: python
    pythonVersion: 3.9.16
    buildCommand: pip install -r requirements.txt
    startCommand: python blood_grp.py
    env:
      - key: PYTHON_VERSION
        value: 3.9.16 